### ISSUE TITLE
Frequently crashed with fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by chhsiao1981** [ailabstw/go-pttai#136]
#### Version information:

Gptt
Version: 0.1.2
Git Commit: d38aa01e43b4443b4733ba42aad97fa076105029
Architecture: amd64
Go Version: go1.11.4
Operating System: darwin

#### Type:

Bug

#### Description:

1. testp2p
2. gptt "--rpcvhosts" "${RPC_VHOST}" "--private-as-public" "--testp2p" "--httpdir" "/static" "--httpaddr" "0.0.0.0:9774" "--rpcaddr" "0.0.0.0" "--exthttpaddr" "${EXT_HTTP_ADDR}" "--extrpcaddr" "${EXT_API_ADDR}"
3. After adding more than 10 friends, sending many messages, and waiting for few hours.

**Comment by chhsiao1981** [comment]
goroutine 1751 [running]:
runtime.throw(0xfd2dff, 0x21)
        /usr/local/go/src/runtime/panic.go:608 +0x72 fp=0xc0073e9110 sp=0xc0073e90e0 pc=0x42eb42
runtime.mapaccess2(0xe54680, 0xc000263da0, 0xc0073e9218, 0x4, 0x2)
        /usr/local/go/src/runtime/map.go:453 +0x223 fp=0xc0073e9158 sp=0xc0073e9110 pc=0x410243
github.com/ailabstw/go-pttai/service.(*PttPeerSet).Peer(0xc0003712c0, 0xc0073e9218, 0xc0073e9201, 0x0)
        /go/src/github.com/ailabstw/go-pttai/build/_workspace/src/github.com/ailabstw/go-pttai/service/ptt_peer_set.go:353 +0x60 fp=0xc0073e9190 sp=0xc0073e9158 pc=0xad0000
github.com/ailabstw/go-pttai/service.(*BaseProtocolManager).RegisterPeer(0xc00052ee00, 0xc0064d6500, 0x4, 0xc0073e95e8, 0x1d36140)
        /go/src/github.com/ailabstw/go-pttai/build/_workspace/src/github.com/ailabstw/go-pttai/service/protocol_manager_utils_peer.go:55 +0x1dd fp=0xc0073e9470 sp=0xc0073e9190 pc=0xaaee5d
github.com/ailabstw/go-pttai/account.(*ProtocolManager).RegisterPeer(0xc000122c60, 0xc0064d6500, 0x4, 0x0, 0x0)
        /go/src/github.com/ailabstw/go-pttai/build/_workspace/src/github.com/ailabstw/go-pttai/account/protocol_manager_utils_peer.go:56 +0x42 fp=0xc0073e94a8 sp=0xc0073e9470 pc=0xb84f82
github.com/ailabstw/go-pttai/service.PMHandleMessageWrapper(0x1206560, 0xc000122c60, 0xc005cac9a0, 0xc006627ce0, 0x60, 0x60, 0xc0064d6500, 0x0, 0x0)
        /go/src/github.com/ailabstw/go-pttai/build/_workspace/src/github.com/ailabstw/go-pttai/service/protocol_manager_utils_handle_message.go:136 +0x892 fp=0xc0073e9770 sp=0xc0073e94a8 pc=0xaa32b2
github.com/ailabstw/go-pttai/service.(*BasePtt).HandleCodeOp(0xc0001bc380, 0xc005cac9a0, 0xc006627ce0, 0x60, 0x60, 0xc0064d6500, 0x60, 0x0)
        /go/src/github.com/ailabstw/go-pttai/build/_workspace/src/github.com/ailabstw/go-pttai/service/ptt_utils_handle_message.go:203 +0x2e4 fp=0xc0073e9868 sp=0xc0073e9770 pc=0xad8344
github.com/ailabstw/go-pttai/service.(*BasePtt).HandleMessage(0xc0001bc380, 0x4, 0xc0072deaf0, 0xc0064d6500, 0xbf0cc71d86acca69, 0x514103f760)
        /go/src/github.com/ailabstw/go-pttai/build/_workspace/src/github.com/ailabstw/go-pttai/service/ptt_utils_handle_message.go:89 +0x644 fp=0xc0073e9ac8 sp=0xc0073e9868 pc=0xad6e24
github.com/ailabstw/go-pttai/service.(*BasePtt).HandleMessageWrapper(0xc0001bc380, 0xc0064d6500, 0x0, 0x0)
        /go/src/github.com/ailabstw/go-pttai/build/_workspace/src/github.com/ailabstw/go-pttai/service/ptt_utils_handle_message.go:49 +0x3f7 fp=0xc0073e9ce0 sp=0xc0073e9ac8 pc=0xad6507
github.com/ailabstw/go-pttai/service.(*BasePtt).HandlePeer(0xc0001bc380, 0xc0064d6500, 0x0, 0x0)
        /go/src/github.com/ailabstw/go-pttai/build/_workspace/src/github.com/ailabstw/go-pttai/service/ptt_utils_peer.go:76 +0x2b2 fp=0xc0073e9df8 sp=0xc0073e9ce0 pc=0xad9c62
github.com/ailabstw/go-pttai/service.(*BasePtt).GenerateRun.func1(0xc006972180, 0x11ecb00, 0xc00697e000, 0x0, 0x0)
        /go/src/github.com/ailabstw/go-pttai/build/_workspace/src/github.com/ailabstw/go-pttai/service/ptt_service_utils.go:68 +0x298 fp=0xc0073e9f00 sp=0xc0073e9df8 pc=0xae5cb8
github.com/ailabstw/go-pttai/p2p.(*Peer).startProtocols.func1(0xc00697e000, 0xc006972180, 0x11ecb00, 0xc00697e000)
        /go/src/github.com/ailabstw/go-pttai/build/_workspace/src/github.com/ailabstw/go-pttai/p2p/peer.go:368 +0x66 fp=0xc0073e9fc0 sp=0xc0073e9f00 pc=0xa17a86
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc0073e9fc8 sp=0xc0073e9fc0 pc=0x45f051
created by github.com/ailabstw/go-pttai/p2p.(*Peer).startProtocols
        /go/src/github.com/ailabstw/go-pttai/build/_workspace/src/github.com/ailabstw/go-pttai/p2p/peer.go:367 +0x1fb

goroutine 1 [select, 5 minutes]:
main.WaitNode(0xc00016e000, 0xc0061e3fc0, 0xc00016e000, 0xc0061e3fc0)
        /go/src/github.com/ailabstw/go-pttai/build/_workspace/src/github.com/ailabstw/go-pttai/cmd/gptt/gptt.go:209 +0x287
main.gptt(0xc000156f20, 0x18, 0xc00010dd38)
        /go/src/github.com/ailabstw/go-pttai/build/_workspace/src/github.com/ailabstw/go-pttai/cmd/gptt/gptt.go:106 +0x35d
github.com/ailabstw/go-pttai/vendor/gopkg.in/urfave/cli%2ev1.HandleAction(0xe2f620, 0x1118cb8, 0xc000156f20, 0xc000156f20, 0xc00010df28)
        /go/src/github.com/ailabstw/go-pttai/build/_workspace/src/github.com/ailabstw/go-pttai/vendor/gopkg.in/urfave/cli.v1/app.go:490 +0xc8
github.com/ailabstw/go-pttai/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc0000e9d40, 0xc0000300f0, 0xf, 0xf, 0x0, 0x0)
        /go/src/github.com/ailabstw/go-pttai/build/_workspace/src/github.com/ailabstw/go-pttai/vendor/gopkg.in/urfave/cli.v1/app.go:264 +0x59d
main.main()
        /go/src/github.com/ailabstw/go-pttai/build/_workspace/src/github.com/ailabstw/go-pttai/cmd/gptt/main.go:133 +0x112

**Comment by chhsiao1981** [comment]
Found that it's incorrect implementation in pm.RegisterPeer.

#137 intends to fix the issue.
